// <auto-generated />
using System;
using Credit_Card_Fraud_Detection.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Credit_Card_Fraud_Detection.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251222035956_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CCFD.Models.FraudAlert", b =>
                {
                    b.Property<long>("alertID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("alertID"));

                    b.Property<string>("alertStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("decision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("riskScore")
                        .HasColumnType("float");

                    b.Property<long>("txnID")
                        .HasColumnType("bigint");

                    b.HasKey("alertID");

                    b.HasIndex("txnID");

                    b.ToTable("FraudAlerts");
                });

            modelBuilder.Entity("CCFD.Models.TxnTable", b =>
                {
                    b.Property<long>("txnID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("txnID"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isFraud")
                        .HasColumnType("bit");

                    b.Property<bool?>("modelPredicted")
                        .HasColumnType("bit");

                    b.Property<double?>("modelRiskScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("timeStamp")
                        .HasColumnType("datetime2");

                    b.Property<long>("userID")
                        .HasColumnType("bigint");

                    b.HasKey("txnID");

                    b.HasIndex("userID");

                    b.ToTable("TxnTables");
                });

            modelBuilder.Entity("CCFD.Models.Users", b =>
                {
                    b.Property<long>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("userID"));

                    b.Property<long?>("city_pop")
                        .HasColumnType("bigint");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("job")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("joinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CCFD.Models.FraudAlert", b =>
                {
                    b.HasOne("CCFD.Models.TxnTable", "txnTable")
                        .WithMany("FraudAlerts")
                        .HasForeignKey("txnID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("txnTable");
                });

            modelBuilder.Entity("CCFD.Models.TxnTable", b =>
                {
                    b.HasOne("CCFD.Models.Users", "user")
                        .WithMany("Transactions")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("CCFD.Models.TxnTable", b =>
                {
                    b.Navigation("FraudAlerts");
                });

            modelBuilder.Entity("CCFD.Models.Users", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
