// <auto-generated />
using System;
using Credit_Card_Fraud_Detection.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Credit_Card_Fraud_Detection.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeviceHistory", b =>
                {
                    b.Property<long>("deviceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("deviceID"));

                    b.Property<string>("deviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("firstUseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("lastUseDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("userID")
                        .HasColumnType("bigint");

                    b.HasKey("deviceID");

                    b.HasIndex("userID");

                    b.ToTable("DeviceHistory");
                });

            modelBuilder.Entity("FraudAlert", b =>
                {
                    b.Property<long>("alertID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("alertID"));

                    b.Property<string>("alertStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("decision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("riskScore")
                        .HasColumnType("float");

                    b.Property<long>("txnID")
                        .HasColumnType("bigint");

                    b.HasKey("alertID");

                    b.HasIndex("txnID");

                    b.ToTable("FraudAlerts");
                });

            modelBuilder.Entity("TxnTable", b =>
                {
                    b.Property<long>("txnID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("txnID"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("deviceID")
                        .HasColumnType("bigint");

                    b.Property<bool?>("isFraud")
                        .HasColumnType("bit");

                    b.Property<bool?>("modelPredicted")
                        .HasColumnType("bit");

                    b.Property<double?>("modelRiskScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("timeStamp")
                        .HasColumnType("datetime2");

                    b.Property<long>("userID")
                        .HasColumnType("bigint");

                    b.HasKey("txnID");

                    b.HasIndex("deviceID");

                    b.HasIndex("userID");

                    b.ToTable("TxnTables");
                });

            modelBuilder.Entity("Users", b =>
                {
                    b.Property<long>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("userID"));

                    b.Property<long?>("city_pop")
                        .HasColumnType("bigint");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("job")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("joinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DeviceHistory", b =>
                {
                    b.HasOne("Users", "users")
                        .WithMany("deviceHistories")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("users");
                });

            modelBuilder.Entity("FraudAlert", b =>
                {
                    b.HasOne("TxnTable", "transaction")
                        .WithMany("FraudAlerts")
                        .HasForeignKey("txnID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("transaction");
                });

            modelBuilder.Entity("TxnTable", b =>
                {
                    b.HasOne("DeviceHistory", "device")
                        .WithMany("txnTables")
                        .HasForeignKey("deviceID");

                    b.HasOne("Users", "user")
                        .WithMany("Transactions")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("device");

                    b.Navigation("user");
                });

            modelBuilder.Entity("DeviceHistory", b =>
                {
                    b.Navigation("txnTables");
                });

            modelBuilder.Entity("TxnTable", b =>
                {
                    b.Navigation("FraudAlerts");
                });

            modelBuilder.Entity("Users", b =>
                {
                    b.Navigation("Transactions");

                    b.Navigation("deviceHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
